### ISSUE TITLE
Document GPG4Win Hack

### ISSUE THREAD

**Issue by metcalfc** [rupor-github/win-gpg-agent#15]
I got this working with GPG4Win because for whatever reason I couldn't get the regular gnupg to work with my Yubikey. 

I followed the flow and only made two changes:

```agent-gui.conf
gpg:
  install_path: "${ProgramFiles(x86)}\\GnuPG"
  homedir: "${APPDATA}\\gnupg"
  socketdir: "${APPDATA}\\gnupg"
```

And I set:

```
export WSL_AGENT_HOME=/home/USERNAME/winhome/AppData/Roaming/gnupg
```

And it works on both sides. WSL2 and Windows. If you want I'll do the README patch I just wanted to check if you would even want to document it since its outside what you're developing and testing for.

Thanks for this. Its great.

**Comment by rupor-github** [comment]
I do not mind documenting it - just want to understand it first :) How do you use WSL_AGENT_HOME which you set ?

**Comment by metcalfc** [comment]
Thanks for the detail, that helped me understand a little more about what was happening. So I was incorrect about needing to set `WSL_AGENT_HOME`. The only change is to set the homedir and sockdir to the same location which for gpg4win is Roaming. 

The rest is stock per your instructions. `socat` is driving. 

```
metcalfc 13577    12  0 13:01 ?        00:00:00 socat UNIX-LISTEN:/home/metcalfc/.gnupg/S.
metcalfc 13582    12  0 13:01 ?        00:00:00 socat UNIX-LISTEN:/home/metcalfc/.gnupg/S.
metcalfc 13587    12  0 13:01 ?        00:00:00 socat UNIX-LISTEN:/home/metcalfc/.gnupg/S.
```
I suppose I run multiple distros in that Docker Desktop is one and I've got Ubuntu on the other. But I only use one for my actual env.

gpg in Windows is: 
```
gpg (GnuPG) 2.2.28
libgcrypt 1.8.8
Copyright (C) 2021 g10 Code GmbH
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: C:/Users/metca/AppData/Roaming/gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```
On the Ubuntu side:
```
gpg (GnuPG) 2.3.3
libgcrypt 1.9.4
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/metcalfc/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
AEAD: EAX, OCB
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

I'm not sure where to open a separate ticket for gnupg not working with my new'ish Yubikey. But no amount of fighting it made scdaemon work. Where it just works with gpg4win. 

Don't need to reopen this but hopefully this issue helps someone in the future.

**Comment by felegy** [comment]
Hi @metcalfc!

Probably I have an idea for your new Yubikey problem. Maybe the new key has a new reader name? Check this doc: https://github.com/drduh/YubiKey-Guide#windows-1

**Comment by rupor-github** [comment]
This "hack" directly contradicts what was written in the readme from the day one: "NOTE that WSL1/WSL2 distribution use case (while seems local and Windows native) does not mean that you should directly share gpg databases from Windows end even if you technically could."
