### ISSUE TITLE
Authentication fails if more than 1 smart card is connected

### ISSUE THREAD

**Issue by kwinz** [rupor-github/win-gpg-agent#17]
Hi,

I am using a Windows `Virtual Smartcard` that is backed by my TPM and stores the client key for my OpenVPN tunnel.
And I am using a ReinerSCT smartcard reader with an OpenPGP card to authenticate with win-gpg-agent on my SSH server.
If I use them in isolation everything works great. But if I have both of those smart card readers connected then:

![does-not-work](https://user-images.githubusercontent.com/588533/140929904-d0a34035-a94e-486b-a741-3387f50c6a7b.PNG)
the agent only finds one key, which is refused by the SSH server.

Only if I manually through the device manager disable the `Virtual Smartcard`, which as far as I can tell is a whole virtual reader, then the agent finds 2 keys, and one of them is accepted from the SSH server:
![works](https://user-images.githubusercontent.com/588533/140930120-a5f47c95-29cc-4fb4-9793-e802127e03cd.PNG)

I would ask that the `win-gpg-agent` can be configured as to which reader/smart card it should use. And if that is not possible, it should query all readers/smart cards for valid keys and present all of them to the SSH server in expectation that one of them is authorized to authenticate.

**Comment by rupor-github** [comment]
I am afraid this is not related to `win-gpg-agent` as it does not do anything by itself - this is why it is called "Windows helpers for GnuPG tools suite" and why documentation says "Make sure GnuPG works. Create/import keys, setup smart cards, etc.". All helper does it accepts request and sends it (translated) to GnuPG `gpg-agent` and then translates back returned response. If `gpg-agent` itself has support for multiple cards ("it should query all readers/smart cards for valid keys and present all of them to the SSH server in expectation that one of them is authorized to authenticate") - you'd get this functionality. If original GnuPG software does not support it - `win-gpg-agent` would not support it either. By my reading GnuPG does not support this scenario: https://dev.gnupg.org/T1621. Please, make sure that what you want is achievable using GnuPG tools - if it does and something is missing, I am willing to work on adding it. Other wise I do not see how I could help you here.

**Comment by kwinz** [comment]
Thanks for pointing me in the right direction and even linking the relevant upstream issue. Much appreciated!

**Comment by kwinz** [comment]
@rupor-github Just to confirm I get this right on the upstream issue report: `win-gpg-agent` is including/bundling version `gnupg 2.3.2` right now? At least it says `v1.3.2 / 2021-08-25 * Changes for gnupg 2.3.2` in the change log.

The status window is broken right now and doesn't display anything:
![image](https://user-images.githubusercontent.com/588533/141439007-624a51e9-04a6-4722-bfca-ce0b39674149.png)

**Comment by kwinz** [comment]
Oh never mind. I just realized that the gpg agent is not bundled with `win-gpg-agent` at all and I had installed it separately. Sorry for the noise!

**Comment by kwinz** [comment]
Upgraded to version `gnupg-w32-2.3.3_20211012`. Issue still exists. Made an upstream issue comment now:
https://dev.gnupg.org/T1621#151776

**Comment by rupor-github** [comment]
Mirco, obtaining a version is a simple `gpg --version` with following string split. If you are running daily build or format of this string changed upstream - it could be empty. I will take care of this in upcoming release, but it is not critical and does not affect what program does.

**Comment by kwinz** [comment]
This is what I get:
```
gpg-agent --version
gpg-agent[3564]: C:/Users/Markus/AppData/Roaming/gnupg/gpg-agent.conf:2: obsolete option "use-standard-socket" - it has no effect
gpg-agent (GnuPG) 2.3.3
libgcrypt 1.9.4
Copyright (C) 2021 g10 Code GmbH
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

and with 

```
gpg-agent --version 2> nul
gpg-agent (GnuPG) 2.3.3
libgcrypt 1.9.4
Copyright (C) 2021 g10 Code GmbH
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by rupor-github** [comment]
Really strange, but in any case - I modified parsing code in the latest release with is now available. Really hope this will help.
