### ISSUE TITLE
Stock install GPG doesn't recognise yubikey

### ISSUE THREAD

**Issue by clumbo** [rupor-github/win-gpg-agent#19]
I am doing the following in the command line after installing via scoop

`gpg --card-status `

This results in the following

```
gpg: can't connect to the gpg-agent: IPC connect call failed
gpg: OpenPGP card not available: No agent running
```

**Comment by rupor-github** [comment]
I am sorry, this is not a proper place to ask about basic GnuPG operations and documentation clearly states that. You need to go to https://gnupg.org/documentation/index.html where proper support channels are listed.

**Comment by clumbo** [comment]
I setup the smartcard it was working.

The trick is not to use the bundled portable version when installing scoop.

With the portable version > 2.3.1 it will not work due to a bug that references a missing gnupg folder> 2.3.1 if you create the gnupg folder next to home you can get the agent to connect via command line but it will not work with win-gpg-agent.

Posting this in case someone else has the problem in the future

https://github.com/ScoopInstaller/Main/issues/2599

thanks

**Comment by rupor-github** [comment]
Assuming by bundled you mead scoop install of gnupg (as iposite to any other gnupg installation) I believe you could still use win-gpg-agent with work around suggested in the scoop ticket by changing agent-gui configuration as it has separate config value to point to a socket directory. I also of opinion that change in 2.3.2 is strange and unnecessary, but do not think it is going to be reverted.

**Comment by clumbo** [comment]
Thanks for the reply,

Yes I did try this and it still didn't work
