### ISSUE TITLE
Option to change "Remember me" default toggle in the config

### ISSUE THREAD

**Issue by sitiom** [rupor-github/win-gpg-agent#23]
It would be consistent with what you would expect from the pinentry in Linux/Mac:

![Pinentry](https://merikan.com/files/how-to-sign-git-commits/pinentry-mac.png)

**Comment by rupor-github** [comment]
"Should" is probably a bit of a strong word here really given the fact that on pretty much every platform GnuPG comes with several pinentry varieties :0

I am really hesitant to change what is presently there quickly for several reasons:
1. Backward compatibility - you are the first person to notice the difference :)
2. If I remember correctly at a time when I was writing go-pinentry I tried to copy logic inside of "standard" (if such thing exist) pinentry - it is pretty convoluted and it is entirely possible that I did not get it right, but I honestly tried.
3. Existing way works for a lot of people 

I will put this in a backburner. As soon as I have time I will try to revisit picnentry.c and see if I could make it a bit more logical.

**Comment by sitiom** [comment]
> you are the first person to notice the difference :)

> Existing way works for a lot of people

Yeah but I noticed it because I unknowingly pressed enter not knowing the checkbox was checked by default :( There are also people who don't want to store the credentials in Credential Manager (including me) and I would have to uncheck the box on the pinentry everytime as an effect.

**Comment by rupor-github** [comment]
"I would have to uncheck the box on the pinentry everytime as an effect." - I am not sure this is entirely correct. I think you should be aware of gnupg configuration options instead:
```
--no-allow-external-cache
Tell Pinentry not to enable features which use an external cache for passphrases.

Some desktop environments prefer to unlock all credentials with one master password and may have installed a Pinentry which employs an additional external cache to implement such a policy. By using this option the Pinentry is advised not to make use of such a cache and instead always ask the user for the requested passphrase.
```

**Comment by sitiom** [comment]
Hmm, I reinstalled GnuPG on mac, and it seems that saving to the keychain is checked by default now. I think mine was unchecked by default because it was on an older version:

> @sitiom - how does Mac pinentry behaves: does it remember the state of the "Save in keychain" from the previous run or it always starts unchecked?

On the GPG Suite settings there is an option to toggle that:
![image](https://user-images.githubusercontent.com/56180050/153094883-9da01464-3bf6-48b6-aa9e-8f09c38ec32a.png)

It might make more sense to have an option like that on the `pinentry.conf`

**Comment by rupor-github** [comment]
I was thinking about remembering the state of the last selection and starting with it next time - old Windows tradition. Not really sure - as "Remember for 60 seconds" I think has completely different semantics.

**Comment by rupor-github** [comment]
See https://github.com/rupor-github/win-gpg-agent/releases/tag/v1.6.0

**Comment by sitiom** [comment]
Looks good to me, thanks!
