### ISSUE TITLE
Pinentry Autofocus

### ISSUE THREAD

**Issue by chvolkmann** [rupor-github/win-gpg-agent#24]
Hi,

it would be nice if the pinentry window would automatically catch focus when launching.

Currently, when I try to ssh into a server from Windows Terminal, pinentry opens. But when I start typing, I'm typing into the terminal because the focus is still caught there.

**Comment by rupor-github** [comment]
From the readme:

> gui.pindialog.* - since gpg-agent starts pinentry which in turn calls Windows APIs to show various dialogs often due to the timing resulting dialog could be left in the background. Those parameters specify artificial delay and name/class for window to be attempted to be brought into foreground forcefully.


Did you try increasing "delay" beyond default 300ms? This worked before: issue #6 "pinentry.exe always shows prompts in the background"
