### ISSUE TITLE
Pinentry icon not showing up in taskbar

### ISSUE THREAD

**Issue by rashil2000** [rupor-github/win-gpg-agent#25]
When double-clicking pinentry.exe, a nice icon appears in taskbar:

![image](https://user-images.githubusercontent.com/46838874/153754583-e92222df-3e43-4748-b88b-38e102ae7ff0.png)

But when signing a commit, this appears:

![image](https://user-images.githubusercontent.com/46838874/153754680-14ac6b26-d42e-411b-8668-7c1130b04476.png)

What gives? 🤔

**Comment by rupor-github** [comment]
I do not control this. To the best of my knowledge WinCred API (CredUIPromptForWindowsCredentials) does not allow you to select any icons - when you call it it spawns some .NET based process which actually shown this dialog on your behalf.
