### ISSUE TITLE
Randomly fails over time.

### ISSUE THREAD

**Issue by leoleoasd** [rupor-github/win-gpg-agent#26]
I tried the `win-gpg-agent-relay` script by calling it with `foreground`. In my observation, it randomly fails over time. When it fails, manually open `sorelay.exe` from wsl hangs forever, instead if giving a "Single path to socket should be specified as positional argument, we have 0 parameters instead" prompt.

Opening other windows EXEs like wsl.exe and notepad.exe from wsl works like a charm. Is this a bug of sorelay, or a bug of calling exe in wsl?

**Comment by leoleoasd** [comment]
Restarting windows host seems help.

**Comment by rupor-github** [comment]
I also noticed some random failures - but I do not yet have enough information to either resolve them or to answer your question. In my experience it is usually connected to "sleep" or "hibernation" - but again I do not yet have enough evidence to exactly point it out.

**Comment by leoleoasd** [comment]
>  In my experience it is usually connected to Windows "sleep" or "hibernation" events - but again I do not yet have enough evidence to exactly point it out.

I use `powertoys awake` to prevent my PC from sleeping or hibernation, and I'm still encountering this bug.
I also noticed that sometimes after run sorelay.exe, I also can not run other exes, like cmd.exe.

**Comment by rupor-github** [comment]
I am sure it is infinitely more complicated than simply doing `powertoys awake`. You are probably aware of `vmIdleTimeout` configuration and "The 8 second rule" which messed up my setups more than once. As I said - I do not have enough information to reproduce this reliably, so I cannot identify and fix the issue.

**Comment by rupor-github** [comment]
@leoleoasd you may want to try latest version of win-gpg-agent-relay - I tried to make more reliable

**Comment by leoleoasd** [comment]
Is there a pre-build artifact or a manual and dependences to build? The latest `release` seems based on an older version.

**Comment by rupor-github** [comment]
Script we are talking about is part of the documentation and not part of the build - it is not being installed inside of WSL2 distribution: not sure how to do that and not going to be able to support it.

**Comment by leoleoasd** [comment]
I also noticed that sometimes my gpg socketdir will change to /run/user/$PID. Maybe use `gpgconf --list-dirs socketdir` instead of hard-coding `$HOME/.gnupg/` in the scrript?

**Comment by rupor-github** [comment]
It your script - you can change it at any point any way you want. However usually your gpg socket will change to `run` directory when you have real `gpg-agent` running - which should not happen,

**Comment by leoleoasd** [comment]
The new script is definitely more stable! Thanks for your great work!

**Comment by leoleoasd** [comment]
I encountered this error again, but this time, the bridge between Windows and WSL just breaks with no moves, i.e. I did not put my computer to sleep. It just fails silently. I can clearly tell this because I opened the same file stored in WSL two times, with about approx 2 minutes in between, and it breaks in the second time.

This is definitely a huge bug of WSL, not your repo.

**Comment by rupor-github** [comment]
Did a couple of more changes to the script - now you could un-comment a line and get yourself a nice error.log in the home directory to debug startup issues. Improved error checking a bit. If you want - see if it improves your situation more. Cannot think of anything else....
