### ISSUE TITLE
Release 1.6.0 files are flagged by VirusTotal

### ISSUE THREAD

**Issue by astelmachonak-nydig** [rupor-github/win-gpg-agent#28]
Hi. Not sure if you can do anything with this, but looks like some binaries from 1.6.0 are flagged by VirusTotal: https://www.virustotal.com/gui/file/aee23e5e4f50c4ed8aaeaadd54117c1f85ecaa5679efee9c428197427e01d944/detection

**Comment by rupor-github** [comment]
Apparently not much. I rebuilt everything with go1.17.9 and updated all the dependencies to the latest versions - same results. Should say that "detection" loops pretty fishy to me - depending on if I use .zip file with release or .exe it gives me different results. I guess somebody started using go to build malware and signatures become maked.

**Comment by astelmachonak-nydig** [comment]
Makes sense, thanks for looking. In my particular situation, antivirus detects `sorelay.exe` as malware (at the same time I am using `npiperelay.exe` without issues). However I still use `win-gpg-agent` - just connect WSL to it using https://github.com/BusyJay/gpg-bridge.

**Comment by rupor-github** [comment]
`sorelay` scan by VirusTotal shows exactly the same "signatures" as `agent-gui`:
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/5368784/164032211-92468266-18cd-49f0-8940-06b88fa31702.png">
I guess we have to wait till the AV model gets enough data. I do think, however, that if you download release zip from github and validated its integrity with `minisign` using provided key - there is no virus there.

**Comment by astelmachonak-nydig** [comment]
> sorelay scan by VirusTotal shows exactly the same "signatures" as agent-gui:
Yes, and this also makes me wonder why my particular antivirus  (corporate one) flags `sorelay` and has no concerns about `agent-gui`. Anyway,  thanks for great utility!
