### ISSUE TITLE
Distribution via scoop?

### ISSUE THREAD

**Issue by LostLaplace** [rupor-github/win-gpg-agent#3]
This is a great project! Works well for me and resolves my biggest complaints with the gpg-agent shipped with GnuPG. Any thoughts on distributing this via the scoop package manager? Since scoop provides a vanilla (i.e. not gpg4win) installation of GPG, I think this would fit well in that repository. I'd gladly work toward setting it up on there if you would like!

**Comment by rupor-github** [comment]
I have absolutely no objections to scoop (or for this matter chocolatey) distribution, its just outside of my practical interests (I am not using it 😄). Please, let me know if I could do something to help!

**Comment by LostLaplace** [comment]
Awesome! I may have some time this next weekend to look into it. Setting up sane defaults for the scoop GnuPG installation would be nice.

**Comment by gpailler** [comment]
Hi @LostLaplace,

I just created a scoop manifest for win-gpg-agent. I would love to get your feedback before sending a PR to scoop/extras => https://github.com/gpailler/scoop-apps/blob/master/win-gpg-agent.json

**Comment by rupor-github** [comment]
@gpailler @LostLaplace 

`scoop install https://github.com/rupor-github/win-gpg-agent/releases/latest/download/win-gpg-agent.json`

This way there is no need to maintain separate tracking manifest

**Comment by gpailler** [comment]
Hi @rupor-github ,

Just switched to your manifest and it's working perfectly fine. 
Thanks!

**Comment by LostLaplace** [comment]
Yikes guys sorry I completely went dark there. Great work @gpailler!
