### ISSUE TITLE
don't work on new version

### ISSUE THREAD

**Issue by Andrysky** [rupor-github/win-gpg-agent#31]
on 1.3.0 all work fine
on v1.6.3 i have a error
![image](https://user-images.githubusercontent.com/5894390/169217065-319dd0ea-c7f9-4178-bc5e-d22027f6f5bf.png)

**Comment by krzys-h** [comment]
#18

**Comment by rupor-github** [comment]
If you need help - please share some information, for example how agent was installed, troubleshooting logs, etc.

As you are already aware between 1.3 and 1.6 there were several changes, including "breaking" ones. Several versions of gnupg have been released with changing behavior for portable and non-portable installations. There is troubleshooting section in readme with explains how to get more information.

**Comment by Andrysky** [comment]
updated gpg4win to 4.0.2 seems to work).
