### ISSUE TITLE
Can't get gpg-agent remote forwarding to work

### ISSUE THREAD

**Issue by scriptmelvin** [rupor-github/win-gpg-agent#32]
I installed win-gpg-agent by copy-pasting the powershell commands. I'm using GnuPG 2.3.6 (installed by Gpg4win) on Windows 10 on the local machine, Linux on the remote. My local ssh is a rather old Cygwin one:
```
$ ssh -V
OpenSSH_7.8p1, OpenSSL 1.0.2p  14 Aug 2018
```
I have the following lines in my ssh config, I tried both:
```
#RemoteForward /run/user/1000/gnupg/S.gpg-agent /cygdrive/c/Users/scriptmelvin/AppData/Local/gnupg/agent-gui/S.gpg-agent.extra
RemoteForward /run/user/1000/gnupg/S.gpg-agent C\:/Users/scriptmelvin/AppData/Local/gnupg/agent-gui/S.gpg-agent.extra
```
Connecting using the smartcard works fine, but signing on remote doesn't work (I have imported the public keys on remote):
```
$ ssh -v remote
...
debug1: remote forward success for: listen /run/user/1000/gnupg/S.gpg-agent:-2, connect C:/Users/scriptmelvin/AppData/Local/gnupg/agent-gui/S.gpg-agent.extra:-2
...
$ echo '' | gpg --no-autostart --clearsign
debug1: client_input_channel_open: ctype forwarded-streamlocal@openssh.com rchan 2 win 2097152 max 32768
debug1: client_request_forwarded_streamlocal: /run/user/1000/gnupg/S.gpg-agent
debug1: connect_next: host C:/Users/scriptmelvin/AppData/Local/gnupg/agent-gui/S.gpg-agent.extra ([unix]:C:/Users/scriptmelvin/AppData/Local/gnupg/agent-gui/S.gpg-agent.extra): Bad file descriptor
connect to C:/Users/scriptmelvin/AppData/Local/gnupg/agent-gui/S.gpg-agent.extra port -2 failed: Bad file descriptor
debug1: failure forwarded-streamlocal@openssh.com
gpg: can't connect to the agent: End of file
gpg: no gpg-agent running in this session
debug1: client_input_channel_open: ctype forwarded-streamlocal@openssh.com rchan 2 win 2097152 max 32768
debug1: client_request_forwarded_streamlocal: /run/user/1000/gnupg/S.gpg-agent
debug1: connect_next: host C:/Users/scriptmelvin/AppData/Local/gnupg/agent-gui/S.gpg-agent.extra ([unix]:C:/Users/scriptmelvin/AppData/Local/gnupg/agent-gui/S.gpg-agent.extra): Bad file descriptor
connect to C:/Users/scriptmelvin/AppData/Local/gnupg/agent-gui/S.gpg-agent.extra port -2 failed: Bad file descriptor
debug1: failure forwarded-streamlocal@openssh.com
gpg: can't connect to the agent: End of file
gpg: keydb_search failed: No agent running
gpg: no default secret key: No agent running
gpg: [stdin]: clear-sign failed: No agent running
```
I have `gpgconf --create-socketdir` in remote .bashrc, `StreamLocalBindUnlink yes` in remote sshd_config and `openssh: cygwin` in agent-gui.conf.
agent-gui debug:
```
[agent-gui] 	
	
---------------------------	
GnuPG version:	
---------------------------	
2.3.6 	
	
---------------------------	
gpg-agent command line:	
---------------------------	
C:\Program Files (x86)\gnupg\bin\gpg-agent.exe --homedir C:\Users\scriptmelvin\AppData\Roaming\gnupg --ssh-fingerprint-digest SHA256 --use-standard-socket --enable-ssh-support --enable-putty-support --daemon --pinentry-program C:\Users\scriptmelvin\win-gpg-agent\pinentry.exe	
	
---------------------------	
gpg-agent home directory:	
---------------------------	
C:\Users\scriptmelvin\AppData\Roaming\gnupg	
	
---------------------------	
gpg-agent sockets directory:	
---------------------------	
C:\Users\scriptmelvin\AppData\Local\gnupg	
	
---------------------------	
agent-gui AF_UNIX and Cygwin sockets directory:	
---------------------------	
C:\Users\scriptmelvin\AppData\Local\gnupg\agent-gui	
	
---------------------------	
agent-gui SSH named pipe:	
---------------------------	
\\.\pipe\openssh-ssh-agent	
	
---------------------------	
gpg-agent XAgent protocol socket on TCP:	
---------------------------	
localhost:1755	
	
[agent-gui] [1652980839198440200] Accepted request from C:\Users\scriptmelvin\AppData\Local\gnupg\agent-gui\S.gpg-agent.ssh.cyg	
```
What am I doing wrong?

**Comment by rupor-github** [comment]
Not sure but as a general note the only form of redirection between Windows and Linux available is port redirection.

`RemoteForward /run/user/1000/gnupg/S.gpg-agent C\:/Users/scriptmelvin/AppData/Local/gnupg/agent-gui/S.gpg-agent.extra` looks to me like domain socket redirection which has never worked with any Windows ssh I have ever tried.

**Comment by scriptmelvin** [comment]
Oh, that's unfortunate... I hoped because the readme says `create AF_UNIX socket counterparts for Assuan sockets from gpg-agent (except "browser" and "ssh" ones) and handle translation.` I could stay clear of socat...

If Cygwin ssh can't use them, what is the purpose of the ...\gnupg\agent-gui\* sockets? What are they anyway?

**Comment by rupor-github** [comment]
Even Windows implementation of openssh cannot presently redirect AF_UNIX sockets to the best of my knowledge. And you are talking about using **old** cygwin implementation which uses its own protocol to replace AF_UNIX sockets with TCP sockets with additional security on top: https://stackoverflow.com/questions/23086038/what-mechanism-is-used-by-msys-cygwin-to-emulate-unix-domain-sockets. 

You could see the purpose of all agent-gui sockets on the diagram in readme - different implementations of different protocols for different connecting programs. There are Assuan sockets, Cygwin sockets, XShell sockets, AF_UNIX sockets.... But there is also a TCP port which could be used to redirect gpg-extra - I am using it to remote private key quite successfully.

**Comment by scriptmelvin** [comment]
Thank you for the explanation, it's clear to me now. It works like a charm now with extra_port and socat on the linux side.

Thank you for this very useful software!
