### ISSUE TITLE
win-gpg-agent-relay can't work when the ssh-agent has no identities

### ISSUE THREAD

**Issue by Editst** [rupor-github/win-gpg-agent#33]
I use the Yubikey to store my private key, when I don't insert it into my computer, `ssh-add -L` will exit with code 1 because there is no private key in gpg.

https://github.com/rupor-github/win-gpg-agent/blob/9ba9d9408bb8e969f0d0a9ba91905381c1440f7e/docs/win-gpg-agent-relay#L194

Your script will exit in this case, is there a better way to check ssh agent?

Thanks!

**Comment by rupor-github** [comment]
Do not have Yubikey - really cannot answer this. I was under impression that "ssh-add -L" does not need any private keys: "Lists public key parameters of all identities currently represented by the agent."

**Comment by Editst** [comment]
If there is no private key in gpg, ssh-add will return like this, even if there is a public key in gpg.

```
ssh-add -L
The agent has no identities.
```

**Comment by rupor-github** [comment]
Do you think this is something to be properly addressed on gpg end of things?

In any case if you could try something like this:
```bash
res=`SSH_AUTH_SOCK="$HOME/.gnupg/S.gpg-agent.ssh" ssh-add -L 2>&1`
if [ "$?" -ne 0 ]; then
  if ! echo "${res}" | grep -q "The agent has no identities"; then
    die "Failure communicating with ssh-agent"
  fi
fi
```
If this works - I could modify `win-gpg-agent-relay` accordingly

**Comment by Editst** [comment]
I think gpg has worked properly in this case, so it should be handled specially. And this codes works for me, thanks.
