### ISSUE TITLE
pinentry.exe always shows prompts in the background

### ISSUE THREAD

**Issue by jamiehankins** [rupor-github/win-gpg-agent#6]
Several times, I've done a check-in, then gone on with some other task not noticing that there's a pop-up hidden, waiting for my PIN. Signed commits are new to me, so I'm not used to having to do that.

I know almost nothing about golang. This project is the first time I've even looked at golang source code, so take what I say with a grain of salt.

I see in credui.go that you call win.SetForegroundWindow. I assume that your win.FindWindow works. I can't spare the time to figure out how to debug golang right now (sorry).

I did find a couple of articles that might help. The problem might be that the process that launches pinentry.exe is not in the foreground. If it's not a GUI app, then this may not be practical to solve.

https://github.com/skratchdot/open-golang/issues/16#issuecomment-693687428
https://stackoverflow.com/a/19136480/645431

**Comment by jamiehankins** [comment]
Repeating the caveot that I don't know what I'm doing with golang, but this might fix it. I'll see if I can figure out how to build and test it.

```
diff --git a/pinentry/client.go b/pinentry/client.go
index 26d7538..c9b6ed6 100644
--- a/pinentry/client.go
+++ b/pinentry/client.go
@@ -6,6 +6,8 @@ import (
        "strconv"
        "time"

+       "github.com/lxn/win"
+       "github.com/lxn/win/kernel32"
        assuan "github.com/rupor-github/win-gpg-agent/assuan/client"
        "github.com/rupor-github/win-gpg-agent/assuan/common"
 )
@@ -20,6 +22,9 @@ type Client struct {

 // Launch starts pinentry binary found in directories from PATH envvar and creates pinentry.Client for interaction with it.
 func Launch() (*Client, error) {
+       if hwnd := kernel32.GetConsoleWindow(); hwnd != 0 {
+               win.SetForegroundWindow(hwnd)
+       }
        cmd := exec.Command("pinentry")

        c := new(Client)
```

**Comment by rupor-github** [comment]
Did you tried adjusting timeout and it did not help? 

Code you are trying to modify is part of assuan protocol. In our case pinentry is not started from go - it is started by gnupg proper (which is C code from original gpg distro), so no, I am pretty sure it would not help...

**Comment by jamiehankins** [comment]
No, I committed that comment before I saw your response. I'll give that a try, thanks.

**Comment by jamiehankins** [comment]
Changing it to 500ms seems to have helped. Thanks.

**Comment by clumbo** [comment]
I too have this problem.

I can't find the documentation for where this timeout is supposed to go?

**Comment by rupor-github** [comment]
From the README:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/5368784/142743604-0517dcfe-4e85-46f5-bd42-07df53ec7b9f.png">
