### ISSUE TITLE
agent-gui doesn't find gpg-agent sockets

### ISSUE THREAD

**Issue by aluki** [rupor-github/win-gpg-agent#7]
I've detected this problem with latest version of win-gpg-agent and version 2.3.2 of GnuPG. The socket files are no more created in ${APPDATA}/gnupg but inside ${LOCALAPPDATA}/gnupg. agent-gui passes the ${APPDATA}/gnupg as homedir to gpg-agent and it expects the agent creates the socket files there. But this version uses the LOCALAPPDATA, so agent-gui exits.

``` text
PS C:\Users\alberto\Downloads\win-gpg-agent> gpgconf --list-dirs
sysconfdir:C%3a\ProgramData\GNU\etc\gnupg
bindir:C%3a\Program Files (x86)\gnupg\bin
libexecdir:C%3a\Program Files (x86)\gnupg\bin
libdir:C%3a\Program Files (x86)\gnupg\lib\gnupg
datadir:C%3a\Program Files (x86)\gnupg\share\gnupg
localedir:C%3a\Program Files (x86)\gnupg\share\locale
socketdir:C%3a\Users\alberto\AppData\Local\gnupg
dirmngr-socket:C%3a\Users\alberto\AppData\Local\gnupg\S.dirmngr
keyboxd-socket:C%3a\Users\alberto\AppData\Local\gnupg\S.keyboxd
agent-ssh-socket:C%3a\Users\alberto\AppData\Local\gnupg\S.gpg-agent.ssh
agent-extra-socket:C%3a\Users\alberto\AppData\Local\gnupg\S.gpg-agent.extra
agent-browser-socket:C%3a\Users\alberto\AppData\Local\gnupg\S.gpg-agent.browser
agent-socket:C%3a\Users\alberto\AppData\Local\gnupg\S.gpg-agent
homedir:C%3a\Users\alberto\AppData\Roaming\gnupg
PS C:\Users\alberto\Downloads\win-gpg-agent>          
```

![image](https://user-images.githubusercontent.com/3134297/134998930-deabe44d-c9fd-404e-ba55-a5414611a97e.png)

``` text
[12040] [agent-gui] Executing: C:\Program Files (x86)\gnupg\bin\gpg-agent.exe --homedir C:\Users\alberto\AppData\Roaming\gnupg --ssh-fingerprint-digest SHA256 --use-standard-socket --enable-ssh-support --enable-putty-support --pinentry-program C:\Users\alberto\Downloads\win-gpg-agent\pinentry.exe --daemon
[12040] [agent-gui] Forcefully killing gpg-agent
```

![image](https://user-images.githubusercontent.com/3134297/134999024-dcb65385-b44d-4a61-960e-6ddda7078136.png)

**Comment by rupor-github** [comment]
Hello - you are right and there was an update to the program issued after
2.3.2 was released. Depending on how you install/update however old
configuration file could be kept back resulting in problem you describe. I
am not really sure what could be done.

**Comment by aluki** [comment]
I've installed GnuPG using `winget` and win-gpg-agent by downloading and uncompressing it. I guess you refer to using scoop to install both.

My idea is to add another option to configuration file `gpg.socketdir` as `gpgconf` has to specify where GnuPG will create sockets. Works for you?

**Comment by rupor-github** [comment]
I still do not see why new configuration option is needed. Existing configuration already has everything necessary - I think you just need to specify proper place for 2.3.2

**Comment by aluki** [comment]
Do you know how can I change the `socketdir` option?

**Comment by rupor-github** [comment]
I am running gpg 2.3.2 installed via scoop for more than a month on multiple boxes. I think there are enough levers in gpg.conf, gpg-agent.conf and config for win agent to point to the same directory no matter how it was installed. I am presently traveling but will try to find time to repeat what you do - just cannot promise rapid response.

**Comment by aluki** [comment]
Thank you.... I'll try it on my own. Wish me luck 😄

**Comment by aluki** [comment]
I've been looking at the source code of GnuPG and, as the function `_gnupg_socketdir_internal` (called from `gnupg_socketdir`), the path is hardcoded https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=common/homedir.c;h=7969a2c2e82879f126a64285d0591b09637b1b9b;hb=3bf8d7e1b7e0482f698b54a6975bdd9aa354244e#l612. There is no way (as far as I've understood) to change it. The only options are a portable app or using another home dir than the usual. This case is not the default way if you install GnuPG with the installer. So I think it is useful to add the option to win-gpg-agent so you can specify where the sockets are. A sane default of using homedir if it is different than usual homedir or the ${LOCALAPPDATA] if not.

**Comment by rupor-github** [comment]
@aluiki - I am back from vacation and will take a look at this time permitting upcoming week.

**Comment by rupor-github** [comment]
@aluki Alberto, as described in README there is `gpg.homedir` option (in agent-gui.conf file). Currently in the absence of configuration file it will be set to "${APPDATA}\\gnupg" (which was default before 2.3.2). And looks like this is what causing "--homedir C:\Users\alberto\AppData\Roaming\gnupg" and an error as it should be "--homedir C:\Users\alberto\AppData\Local\gnupg" instead.  If I understand it correctly 2.3.2 now uses "${LOCALAPPDATA}\\gnupg" as GNUPG_DEFAULT_HOMEDIR, so it looks to me that all it takes for your setup to work is to create agent-gui.conf with following content:

```
gpg
    homedir: "${LOCALAPPDATA}\\gnupg"
```

In order to work properly. As I suspected from the beginning no changes in the code or new parameters are needed.
