### ISSUE TITLE
Unable to locate module github.com/rupor-github/win-gpg-agent/misc

### ISSUE THREAD

**Issue by aluki** [rupor-github/win-gpg-agent#8]
When I execute `go get`, I'm getting

```text
github.com/rupor-github/win-gpg-agent/cmd/agent imports
        github.com/rupor-github/win-gpg-agent/misc: cannot find module providing package github.com/rupor-github/win-gpg-agent/misc
```

The dir `misc` doesn't exist in the repo and the three binaries call to `misc.GetVersion()`.

**Comment by rupor-github** [comment]
Project is being built by cmake file (which is included) - and that is how versions.go is generated :) I am not interested in supporting "go get" or "go install".
