### ISSUE TITLE
Setting up gpg-agent remoting from Windows to Linux over SSH

### ISSUE THREAD

**Issue by MathiasMagnus** [rupor-github/win-gpg-agent#9]
I tried following your instructions, however I not only managed to "screw up" one of my remote ends. A reboot may solve the issue, but multiple people are using said machine and I don't have the luxury of rebooting it any time.

In the spirit of minimal dependencies I wish to use to the build-in OpenSSH of Windows (which has served me well thus far). I have disabled the ssh-agent service I had previously and registered a scheduled task for running `gpg-agent-gui.exe` which starts fine. The config file I put beside it reads `PS C:\Users\mate> gc C:\Kellekek\WinGpgAgent\agent-gui.conf`:
```yaml
gpg:
  install_path: "C:\\Kellekek\\GnuPG"
  homedir: "${APPDATA}\\gnupg"
gui:
  debug: false
  setenv: true
  openssh: native
  ignore_session_lock: false
  deadline: 1m
  pipe_name: "\\\\.\\pipe\\openssh-ssh-agent"
  homedir: "${LOCALAPPDATA}\\gnupg"
  extra_port: 2850
```
On my local (Windows) box, gpg signature works without password prompt, as it had been remembered.
```
PS C:\Users\mate> "" | gpg --clearsign
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256


-----BEGIN PGP SIGNATURE-----
...
-----END PGP SIGNATURE-----
```
In my SSH config file I have an entry which reads
```
host my_fav_host
        Hostname my_fav_host
        User mate
        ForwardX11 no
        IdentityFile ~/.ssh/id_rsa
        ForwardAgent yes
        AddKeysToAgent yes
        RemoteForward /run/user/1001/gnupg/S.gpg-agent C%3a/Users/mate/AppData/Roaming/gnupg/S.gpg-agent.extra
```
The formatting of the local socket is as such because this is how gpgconf reports it.
```
PS C:\Users\mate> gpgconf
gpg:OpenPGP:C%3a\Kellekek\GnuPG\bin\gpg.exe
gpg-agent:Private Keys:C%3a\Kellekek\GnuPG\bin\gpg-agent.exe
...
```
Having `C:` in the path results in errors while trying to forward the agent.

After I connect to the remote machine, I tried to conjure the proper `socat` incantation, but could not figure what should it be. The example at the end of the README uses WSL, hence it uses localhost:2850 (in the case of my config file), but how on earth would this yield meaningful results in the context of a properly remote Linux node? The `sorelay` sample invocation where the components are described also assume WSL usage, since it invokes sorelay through the `winhome` folder which only exists when the local end is Linux, not Windows. I tried the following paraphrase of things in the README:
```
(socat UNIX-LISTEN:/home/mate/.gnupg/S.gpg-agent,fork EXEC:"c:/Kellekek/WinGpgAgent/sorelay.exe c:/Users/mate/AppData/Roaming/gnupg/S.gpg-agent.extra",nofork &) >/dev/null 2>&1
```
However now when I try to list my secret keys or sign something, it sees no secret keys. Previously before issuing the socat command I had at least broken pipe error messages, indicating it wanted to use the agent, but couldn't. Unfortunately I found no traces of how to undo the effect of socat (or previous attempts that is).

I'm not a total sysadmin noob, but this level of network sorcery is beyond my comfort zone. However working Linux remotes from a Windows devbox is a constant, and I wanted to improve my dev UX of having to deploy my private keys remotely and unlocking them from the command-line by setting GPG_TTY and relying on the unlock timeout to not have to enter passphrases constantly.

_(ps.: is there a way to relate the `GnuPG:PinGO=n/......` entries in the Credential Store to GPG key IDs?)_

**Comment by rupor-github** [comment]
I guess this depends on how you start socat, right? Like pretty much everything else.

As for how to relate entries in "Credential Manager" why would not you try something like:
```
gpg --fingerprint --with-keygrip
```
and/or
```
gpg-connect-agent 'keyinfo --list'
```
?

**Comment by MathiasMagnus** [comment]
Finally, I got it to work. Thanks @rupor-github for all your comments and the actual repo.
The final things missing was socat between the agent socket and 127.0.0.1:2850, but the bashrc fragment for some reason doesn't work as intended (or as I understand).

It seems as if it wanted to check whether redirection works, and if not then it assumes we're using the Windows built-in (aka. Win32-OpenSSH) and if it failed, then we remove the gpg-agent socket and use socat instead.

Even though I'm using Windows built-in ssh:
```
PS C:\Users\mate> gcm ssh | ft -AutoSize

CommandType Name    Version Source
----------- ----    ------- ------
Application ssh.exe 8.1.0.1 C:\Windows\System32\OpenSSH\ssh.exe
```
And even though redirection works:
```
PS C:\Users\mate> ssh remotehost -vvv exit 2>&1 | sls forward

debug1: Remote connections from 127.0.0.1:2850 forwarded to local address 127.0.0.1:2850
debug1: remote forward success for: listen 127.0.0.1:2850, connect 127.0.0.1:2850
debug1: All remote forwarding requests processed
debug1: Requesting authentication agent forwarding.
```
The `ss -a | grep -q ${_sock_name}` command succeeds, always. Even with and without socat running, but redirection only works when socat is running. Hence I disabled the check for now (I'm only ever using one hop from my devbox to the servers, I'll update if I'll be using proxies or multiple SSHs in succession) and I removed the `setsid` part, because as I said, `ss -a | grep -q ${_sock_name}` always succeed and it cannot differentiate between socat already running or not, (I'll have to devise another predicate for that.) and the number of `socat` instances just keep growing, so for the time being their lifetime being tied to my shell is good enough.

Once again, thanks for all your help.

**Comment by rupor-github** [comment]
No prob, happy to hear. The only difference I could think of is the fact the I am running zsh not bash. Here is complete code fragment from my startup and I am using it daily on multiple boxes, sometimes  tunnels running through multiple points :)

```
if [ ${ISWSL} -eq 1 ]; then

    if [ -n ${WSL_AGENT_HOME} ]; then
        export GNUPGHOME=${WSL_AGENT_HOME}
        export SSH_AUTH_SOCK=${WSL_AGENT_HOME}/S.gpg-agent.ssh
    fi
    export BROWSER="${HOME}/winhome/.wsl/gclpr.exe open"

elif [ ${ISWSL} -eq 2 ]; then

    if [ ! -d ${HOME}/.gnupg ]; then
        mkdir ${HOME}/.gnupg
        chmod 0700 ${HOME}/.gnupg
    fi
    if [ -n ${WIN_GNUPG_HOME} ]; then
        # setup gpg-agent socket
        _sock_name=${HOME}/.gnupg/S.gpg-agent
        ss -a | grep -q ${_sock_name}
        if [ $? -ne 0  ]; then
            rm -f ${_sock_name}
            ( setsid socat UNIX-LISTEN:${_sock_name},fork EXEC:"${HOME}/winhome/.wsl/sorelay.exe -a ${WIN_GNUPG_HOME//\:/\\:}/S.gpg-agent",nofork & ) >/dev/null 2>&1
        fi
        # setup gpg-agent.extra socket
        _sock_name=${HOME}/.gnupg/S.gpg-agent.extra
        ss -a | grep -q ${_sock_name}
        if [ $? -ne 0  ]; then
            rm -f ${_sock_name}
            ( setsid socat UNIX-LISTEN:${_sock_name},fork EXEC:"${HOME}/winhome/.wsl/sorelay.exe -a ${WIN_GNUPG_HOME//\:/\\:}/S.gpg-agent.extra",nofork & ) >/dev/null 2>&1
        fi
        unset _sock_name
    fi
    if [ -n ${WIN_AGENT_HOME} ]; then
        # and ssh-agent socket
        export SSH_AUTH_SOCK=${HOME}/.gnupg/S.gpg-agent.ssh
        ss -a | grep -q ${SSH_AUTH_SOCK}
        if [ $? -ne 0  ]; then
            rm -f ${SSH_AUTH_SOCK}
            ( setsid socat UNIX-LISTEN:${SSH_AUTH_SOCK},fork EXEC:"${HOME}/winhome/.wsl/sorelay.exe ${WIN_AGENT_HOME//\:/\\:}/S.gpg-agent.ssh",nofork & ) >/dev/null 2>&1
        fi
    fi
    export BROWSER="${HOME}/winhome/.wsl/gclpr.exe open"

else

    # we are using gpg-agent via systemd when on local native Linux, so do whatever
    if [ -n "${SSH_TTY}"  ] || [ -n "${SSH_CLIENT}"  ]; then
        export BROWSER='gclpr open'
        # setup gpg-agent socket - when connecting using linux we could use stream socket forwading and all this is completly unnecessary
        ## Win32-OpenSSH: RemoteForward 127.0.0.1:19321 127.0.0.1:19321
        ## Otherwise:     RemoteForward /run/user/<USER-ID>/gnupg/S.gpg-agent /home/<USER>/.gnupg/S.gpg-agent.extra
        _sock_name=$(gpgconf --list-dir agent-socket)
        ss -a | grep -q ${_sock_name}
        if [ $? -ne 0  ]; then
            # We came with Win32-OpenSSH, recreate domain socket for remotely forwarded S.gpg-agent.extra
            rm -f ${_sock_name}
            ( setsid socat UNIX-LISTEN:${_sock_name},fork TCP4:127.0.0.1:19321 & ) >/dev/null 2>&1
        fi
        unset _sock_name
    fi

fi
```
